# This is a basic workflow to help you get started with Actions

name: ARCHI-REPORT-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  archi_report:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/alexishfr/archimate-ci-image:5.2.0-dev
    
    name: Deploy Archi report HTML to GitHub Pages
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Deploy Archi report
        id: archi
        run: /opt/Archi/entrypoint.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCHI_REPORT_PATH: "/archi/report"
          GIT_SUBTREE_PREFIX: ".archi_report"
          GITHUB_PAGES_BRANCH: "gh-pages"
          ARCHI_HTML_REPORT_ENABLED: "true"
          ARCHI_JASPER_REPORT_ENABLED: "false"
          ARCHI_JASPER_REPORT_FORMATS: "PDF,DOCX"
          ARCHI_CSV_REPORT_ENABLED: "false"
          ARCHI_EXPORT_MODEL_ENABLED: "false"
