name: JASMINE-MODEL-TESTS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  archi_report:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image:  ghcr.io/alexishfr/archimate-ci-image:5.2.0-test
    
    name: Run Jasmine Tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run jArchi script that launch Jasmine tests
        id: archi
        run: /opt/Archi/entrypoint.sh -application com.archimatetool.commandline.app  -nosplash --script.runScript "/archi/project/run-jasmine-model-tests.ajs" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCHI_HTML_REPORT_ENABLED: "false"
          ARCHI_JASPER_REPORT_ENABLED: "false"
          ARCHI_CSV_REPORT_ENABLED: "false"
          ARCHI_EXPORT_MODEL_ENABLED: "false"
