name: JASMINE-MODEL-TESTS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  jasmine_tests:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    
    container:
      image:  ghcr.io/alexishfr/archimate-script-ci-image:5.2.0-dev
      credentials:
        #username: ${{ github.Actor }}
        #password:  ${{ secrets.GITHUB_TOKEN }}
        password: "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"

    
    name: Run Jasmine Tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check out the model repo
        id: archi-checkout
        run: /opt/Archi/entrypoint.sh 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCHI_HTML_REPORT_ENABLED: "false"
          ARCHI_JASPER_REPORT_ENABLED: "false"
          ARCHI_CSV_REPORT_ENABLED: "false"
          ARCHI_EXPORT_MODEL_ENABLED: "false"
          
      - name: Run jArchi script that launch Jasmine tests
        id: archi-jarchi
        run: /opt/Archi/launcher.sh
        env:
          JASMINE: "true"
